name: "Sample React CI Pipeline /Workflow"

on:
  push:
    branches:
      - main
      - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:                           #ref = https://github.com/actions/setup-node
            - name: "Setup Node JS"
              uses: actions/setup-node@v4        #we are using github action command thats why we are using keyword "uses"
              with:
                node-version: '21'
                # cache: 'npm'
            
            - name: "Check version"
              run: node --version     #we are using a linux command so we are using keyword "run"

            - name: "Clone the repository"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: npm install

            - name: "List Directories"
              run: ls -la